[package]
name = "bluez-sbc-sys"
description = "A very thin wrapper around the SBC codec contained in BlueZ version 4.86.0"
version = "1.0.0"
edition = "2021"

[build-dependencies]
bindgen = "0.68.1"

[dev-dependencies]
hound = "3.5.1"
